# StepUp RepRep is the StepUp extension for Reproducible Reporting.
# Copyright 2024-2026 Toon Verstraelen
#
# This file is part of StepUp RepRep.
#
# StepUp RepRep is free software;  you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# StepUp RepRep is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --
"""Wrapper for Jupyter notebook conversion using nbconvert Python API."""

import argparse
import json
from pathlib import Path

from nbconvert import exporters
from nbconvert.preprocessors import ExecutePreprocessor
from nbformat import read, v4


def main():
    """Main program."""
    args = parse_args()

    if not args.path_nb.endswith(".ipynb"):
        raise ValueError("The notebook file must have extension .ipynb")

    # Read notebook
    notebook = read(args.path_nb, as_version=4)

    # Inject parameters if provided
    if args.parameters is not None:
        parameters_data = json.loads(args.parameters)
        param_lines = [
            "# This cell is automatically generated by srr-convert-jupyter to inject parameters.",
            f"locals().update({json.dumps(parameters_data, ensure_ascii=False)})",
        ]
        cell_id = "srr-convert-jupyter-inject-parameters"
        param_cell = v4.new_code_cell("\n".join(param_lines), id=cell_id)

        # Find the first cell with "parameters" tag and insert after it
        for i, cell in enumerate(notebook.cells):
            if "parameters" in cell.get("metadata", {}).get("tags", []):
                notebook.cells.insert(i + 1, param_cell)
                break
        else:
            raise RuntimeError("No cell with tag 'parameters' found in the notebook.")

    # Execute if requested
    if args.execute:
        ep = ExecutePreprocessor(
            timeout=600,
            kernel_name="python3",
            extra_arguments=["--IPKernelApp.log_level=40"],
        )
        notebook, _resources = ep.preprocess(
            notebook, {"metadata": {"path": str(Path(args.path_nb).parent)}}
        )

    # Get exporter
    exporter_class = exporters.get_exporter(args.to)

    exporter = exporter_class()

    # Convert
    body, _resources = exporter.from_notebook_node(notebook)

    # Write output
    Path(args.path_out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.path_out, "w", encoding="utf-8") as f:
        f.write(body)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="srr-convert-jupyter",
        description="Convert a Jupyter notebook using the nbconvert Python API.",
    )
    parser.add_argument("path_nb", help="The input Jupyter notebook (.ipynb).")
    parser.add_argument("path_out", help="The output file.")
    parser.add_argument(
        "--to",
        default="html",
        help="The output format (html, pdf, latex, markdown, etc.). Default: html",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute the notebook before conversion.",
    )
    parser.add_argument(
        "--parameters",
        type=str,
        help="Arguments to pass to the notebook as a literal JSON string.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    main()
