# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Wrapper for Jupyter notebook conversion using nbconvert Python API."""

import argparse
import json
import os
import sys
from collections.abc import Sequence

from nbclient import NotebookClient
from nbclient.exceptions import CellTimeoutError
from nbconvert import exporters
from nbformat import NotebookNode, read, v4
from path import Path

from stepup.core.extapi import child_env
from stepup.reprep.jupyter_kernel import ipc_kernel_config

__all__ = ("main",)

NO_TIMEOUT_TAG = "stepup-no-timeout"


def main(argv: Sequence[str] | None = None):
    """Main program."""
    args = parse_args(argv)

    if not args.path_nb.endswith(".ipynb"):
        raise ValueError("The notebook file must have extension .ipynb")

    notebook = read(args.path_nb, as_version=4)

    if args.parameters is not None:
        parameters_data = json.loads(args.parameters)
        param_lines = [
            "# This cell is automatically generated by srr-convert-jupyter to inject parameters.",
            f"locals().update({json.dumps(parameters_data, ensure_ascii=False)})",
        ]
        cell_id = "srr-convert-jupyter-inject-parameters"
        param_cell = v4.new_code_cell("\n".join(param_lines), id=cell_id)

        # Find the first cell with "parameters" tag and insert after it
        for i, cell in enumerate(notebook.cells):
            if "parameters" in cell.get("metadata", {}).get("tags", []):
                notebook.cells.insert(i + 1, param_cell)
                break
        else:
            raise RuntimeError("No cell with tag 'parameters' found in the notebook.")

    if args.execute:
        dir_nb = Path(args.path_nb).parent.normpath()
        default_timeout = resolve_timeout(args.timeout)
        with ipc_kernel_config() as config:
            client = NotebookClient(
                notebook,
                config=config,
                timeout=default_timeout,
                timeout_func=lambda cell: get_cell_timeout(cell, default_timeout),
                kernel_name="python3",
                extra_arguments=["--IPKernelApp.log_level=40"],
            )
            try:
                client.execute(cwd=str(dir_nb), env=child_env(dir_nb))
            except CellTimeoutError as exc:
                raise RuntimeError(
                    f"A cell in {args.path_nb} exceeded the timeout of {default_timeout} s. "
                    f"Tag the cell with '{NO_TIMEOUT_TAG}' to disable its timeout, "
                    "or change the timeout with the 'timeout' argument of convert_jupyter() "
                    "or the REPREP_JUPYTER_TIMEOUT environment variable."
                ) from exc

    exporter_class = exporters.get_exporter(args.to)

    exporter = exporter_class()

    body, _resources = exporter.from_notebook_node(notebook)

    Path(args.path_out).parent.normpath().makedirs_p()
    with open(args.path_out, "w", encoding="utf-8") as f:
        f.write(body)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="srr-convert-jupyter",
        description="Convert a Jupyter notebook using the nbconvert Python API.",
    )
    parser.add_argument("path_nb", help="The input Jupyter notebook (.ipynb).")
    parser.add_argument("path_out", help="The output file.")
    parser.add_argument(
        "--to",
        default="html",
        help="The output format (html, pdf, latex, markdown, etc.). Default: html",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute the notebook before conversion.",
    )
    parser.add_argument(
        "--parameters",
        type=str,
        help="Arguments to pass to the notebook as a literal JSON string.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=None,
        help="The timeout in seconds for executing a single cell. "
        "0 disables the timeout. "
        "The default is ${REPREP_JUPYTER_TIMEOUT} or no timeout if the variable is unset. "
        f"Cells tagged {NO_TIMEOUT_TAG} never time out.",
    )
    return parser.parse_args(argv)


def resolve_timeout(timeout: int | None) -> int | None:
    """Combine the `--timeout` option with the `REPREP_JUPYTER_TIMEOUT` environment variable.

    Parameters
    ----------
    timeout
        The value of the `--timeout` option, or `None` if it was not given.

    Returns
    -------
    timeout
        The timeout in seconds, or `None` when no timeout applies.

    Raises
    ------
    ValueError
        When the option or the environment variable is negative or not an integer.
    """
    if timeout is None:
        # Not read with getenv from StepUp Core, which would make it a step dependency.
        # A timeout never changes the result of a successful run,
        # so changing it should not cause notebooks to be executed again.
        value = os.environ.get("REPREP_JUPYTER_TIMEOUT", "").strip()
        if value == "":
            return None
        try:
            timeout = int(value)
        except ValueError as exc:
            raise ValueError(
                f"REPREP_JUPYTER_TIMEOUT must be a non-negative integer, got {value!r}"
            ) from exc
        if timeout < 0:
            raise ValueError(
                f"REPREP_JUPYTER_TIMEOUT must be a non-negative integer, got {value!r}"
            )
    elif timeout < 0:
        raise ValueError(f"The timeout must be a non-negative integer, got {timeout}")
    return None if timeout == 0 else timeout


def get_cell_timeout(cell: NotebookNode, default_timeout: int | None) -> int | None:
    """Return the timeout of a cell, which is `None` for cells tagged `stepup-no-timeout`."""
    if NO_TIMEOUT_TAG in cell.get("metadata", {}).get("tags", []):
        return None
    return default_timeout


if __name__ == "__main__":
    sys.exit(main())
