site_name: StepUp RepRep
repo_url: https://github.com/reproducible-reporting/stepup-reprep
edit_uri: edit/main/docs/

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: Source Code Pro
  features:
  - search.highlight
  - search.suggest
  - search.share
  - navigation.instant
  - navigation.instant.prefetch
  - content.code.copy
  - content.action.edit
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference

nav:
  - Home: index.md
  - installation.md
  - Template Tutorial:
    - from_template/introduction.md
    - from_template/before_you_begin.md
    - from_template/create_or_clone_a_project.md
    - from_template/working_on_a_project.md
  - From Scratch:
    - from_scratch/introduction.md
  - Advanced Topics:
    - advanced_topics/manifest_files.md
    - advanced_topics/tiling_pdfs.md
    - advanced_topics/good_practices.md
  - Reference:
    - reference/stepup.reprep.api.md
    - reference/stepup.reprep.tile_pdf.md
  - changelog.md
  - development.md
  - license.md

exclude_docs: |
  */*/ch*/*.md
  */*/public/*.md

plugins:
- search
- macros
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: ["stepup-reprep"]
        options:
          docstring_style: numpy
          docstring_section_style: list

markdown_extensions:
  - admonition
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
