#!/usr/bin/env python3
from stepup.core.api import static, step
from stepup.reprep.api import compile_typst

static("../doc/", "../doc/main.typ", "../doc/other.typ")
compile_typst("../doc/main.typ")
step(
    "echo 'This sentence is generated by another step.' > ${out}",
    out="generated.typ",
    workdir="../doc",
    optional=True,
)
