#!/usr/bin/env python3
from stepup.core.api import run, static
from stepup.reprep.api import compile_typst

static("../doc/main.typ", "../doc/other.typ")
compile_typst("../doc/main.typ")
run(
    "echo 'This sentence is generated by another step.' > ${out}",
    out="generated.typ",
    workdir="../doc",
    shell=True,
    optional=True,
)
