#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Regenerate `stepup/reprep/zenodo_vocabularies.yaml` from the Zenodo API.

Run this script from the root of the repository:

```bash
python tools/update_zenodo_vocabularies.py
```

It refreshes every vocabulary that the data file already holds.
Extra names on the command line are added to the file.
The changes are printed as a per vocabulary summary of added and removed identifiers,
so that a refresh can be reviewed before it is committed.
"""

import argparse
import datetime
import sys

import attrs
import requests
import yaml
from path import Path


@attrs.define
class Case:
    """A vocabulary name and some related properties."""

    name: str = attrs.field()
    reprep_name: str = attrs.field()
    description: list[str] = attrs.field()


CASES = [
    Case(
        "code:developmentStatus",
        "development_status",
        ["The development status of the software."],
    ),
    Case(
        "code:programmingLanguages",
        "programming_languages",
        ["The programming languages used in the software."],
    ),
    Case(
        "languages",
        "languages",
        ["The natural languages used in the record."],
    ),
    Case(
        "licenses",
        "licenses",
        [
            "The licenses under which the record is released. "
            "When specyfing more than one, "
            "add a paragraph to the description which license applies to which part of the record."
        ],
    ),
    Case(
        "relationtypes",
        "relation_types",
        [
            "The types of relations between this record and other records. ",
            "Select the relation such that the following sentence works: ",
            "*This record {relation_type} the related record*.",
        ],
    ),
    Case(
        "resourcetypes",
        "resource_types",
        ["The types of resources in this record."],
    ),
]

API_URL = "https://zenodo.org/api/vocabularies"

PAGE_SIZE = 500

YAML_PATH = (
    Path(__file__).parent.parent / "stepup" / "reprep" / "zenodo_vocabularies.yaml"
).normpath()

YAML_HEADER = """\
# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Controlled vocabularies of Zenodo.
# Each key is the name of a vocabulary in Zenodo's API
# and holds the identifiers read from https://zenodo.org/api/vocabularies/<name>
# Zenodo extends its vocabularies over time,
# so an identifier may have become valid after this file was written.
#
# Do not edit this file by hand.
# It is regenerated by tools/update_zenodo_vocabularies.py.
#
# Downloaded on ...
"""

MARKDOWN_PATH = (
    Path(__file__).parent.parent / "docs" / "reference" / "zenodo_vocabularies.md"
).normpath()

MARKDOWN_HEADER = """\
<!--
SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
SPDX-License-Identifier: CC-BY-SA-4.0
-->

# Tables of Zenodo Controlled Vocabularies

The tables below are generated by the script
[`tools/update_zenodo_vocabularies.py`](https://github.com/reproducible-reporting/stepup-reprep/blob/main/tools/update_zenodo_vocabularies.py)
which fetches them from `https://zenodo.org/api/vocabularies/<name>`.
A machine-readable version is available at
[`stepup/reprep/zenodo_vocabularies.yaml`](https://github.com/reproducible-reporting/stepup-reprep/blob/main/stepup/reprep/zenodo_vocabularies.yaml).

Last updated on {date}.
"""


def main():
    """Refresh the vocabulary data file and report what changed."""
    args = parse_args()
    old = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8")) if YAML_PATH.exists() else {}
    if len(old) == 0 and args.skip_download:
        raise ValueError(f"{YAML_PATH} is empty, cannot skip downloading.")
    if args.skip_download:
        print(f"Skipping download, reading {YAML_PATH} ...")
        MARKDOWN_PATH.write_text(format_markdown(old), encoding="utf-8")
    else:
        print(f"Downloading vocabularies from {API_URL} ...")
        new = {case.name: download_vocabulary(case.name) for case in CASES}
        new["_date"] = datetime.date.today().isoformat()
        changed = report(old, new)
        if changed:
            print(f"Writing updated {YAML_PATH} ...")
            YAML_PATH.write_text(format_yaml(new), encoding="utf-8")
            print(f"Writing updated {MARKDOWN_PATH} ...")
            MARKDOWN_PATH.write_text(format_markdown(new), encoding="utf-8")
        else:
            print("No changes.")


def parse_args() -> argparse.Namespace:
    """Parse the command line arguments."""
    parser = argparse.ArgumentParser(description="Refresh the Zenodo vocabularies data file.")
    parser.add_argument(
        "-s",
        "--skip-download",
        action="store_true",
        help="Skip downloading the vocabularies from Zenodo's API. "
        "Only format the Markdown file from the existing YAML file.",
    )
    return parser.parse_args()


def download_vocabulary(name: str) -> list[str]:
    """Download all identifiers of one vocabulary from the Zenodo API.

    Parameters
    ----------
    name
        The name of the vocabulary in Zenodo's API, e.g. `licenses`.

    Returns
    -------
    identifiers
        The sorted identifiers of the vocabulary.
    """
    identifiers = set()
    url = f"{API_URL}/{name}?size={PAGE_SIZE}"
    while url is not None:
        res = requests.get(url, timeout=60)
        res.raise_for_status()
        data = res.json()
        identifiers.update(hit["id"] for hit in data["hits"]["hits"])
        url = data.get("links", {}).get("next")
    if len(identifiers) == 0:
        raise ValueError(f"The vocabulary {name} is empty. Is the name correct?")
    return sorted(identifiers)


def format_yaml(vocabularies: dict[str, list[str]]) -> str:
    """Format the vocabularies as the contents of the data file."""
    lines = [YAML_HEADER]
    for name, identifiers in sorted(vocabularies.items()):
        lines.append(f'"{name}":\n')
        lines.extend(f'  - "{identifier}"\n' for identifier in identifiers)
    return "".join(lines)


def format_markdown(vocabularies: dict[str, list[str]]) -> str:
    """Format the vocabularies as a Markdown document."""
    frags = [MARKDOWN_HEADER.format(date=vocabularies["_date"])]
    maxlen = 80
    minspacing = 3
    for case in CASES:
        identifiers = vocabularies[case.name]
        frags.append(f"\n## `{case.reprep_name}`\n\n```text\n")
        colwidth = max(len(identifier) for identifier in identifiers)
        ncol = (maxlen + minspacing) // (colwidth + minspacing)
        identifiers.extend([""] * (ncol - len(identifiers) % ncol))
        nrow = len(identifiers) // ncol
        newline = False
        for i in range(len(identifiers)):
            icol = i % ncol
            irow = i // ncol
            identifier = identifiers[irow + icol * nrow]
            adjusted = identifier.ljust(colwidth + minspacing)
            frags.append(adjusted)
            if i % ncol == ncol - 1:
                frags.append("\n")
                newline = True
            else:
                newline = False
        if not newline:
            frags.append("\n")
        frags.append("```\n")
    return "".join(frags)


def report(old: dict[str, list[str]], new: dict[str, list[str]]) -> bool:
    """Print the added and removed identifiers per vocabulary."""
    changed = False
    merged = {old_name: [] for old_name in old}
    merged.update(new)
    for name, identifiers in sorted(merged.items()):
        added = sorted(set(identifiers) - set(old.get(name, [])))
        removed = sorted(set(old.get(name, [])) - set(identifiers))
        print(f"{name}: {len(identifiers)} identifiers, +{len(added)} -{len(removed)}")
        for identifier in added:
            print(f"  + {identifier}")
            changed = True
        for identifier in removed:
            print(f"  - {identifier}")
            changed = True

    return changed


if __name__ == "__main__":
    sys.exit(main())
