#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Regenerate `stepup/reprep/zenodo_vocabularies.yaml` from the Zenodo API.

Run this script from the root of the repository:

```bash
python tools/update_zenodo_vocabularies.py
```

It refreshes every vocabulary that the data file already holds.
Extra names on the command line are added to the file.
The changes are printed as a per vocabulary summary of added and removed identifiers,
so that a refresh can be reviewed before it is committed.
"""

import argparse
import datetime
import sys
from pathlib import Path

import requests
import yaml

VOCABULARIES_PATH = Path(__file__).parent.parent / "stepup" / "reprep" / "zenodo_vocabularies.yaml"

API_URL = "https://zenodo.org/api/vocabularies"

PAGE_SIZE = 500

HEADER = """\
# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Controlled vocabularies of Zenodo.
# Each key is the name of a vocabulary in Zenodo's API
# and holds the identifiers read from https://zenodo.org/api/vocabularies/<name>
# on {date}.
# Zenodo extends its vocabularies over time,
# so an identifier may have become valid after this file was written.
#
# Do not edit this file by hand.
# It is regenerated by tools/update_zenodo_vocabularies.py.
"""


def main(argv: list[str] | None = None):
    """Refresh the vocabulary data file and report what changed."""
    args = parse_args(argv)
    old = yaml.safe_load(VOCABULARIES_PATH.read_text(encoding="utf-8"))
    names = sorted(set(old) | set(args.names))
    new = {name: download_vocabulary(name) for name in names}
    changed = report(old, new)
    if changed:
        print(f"Writing updated {VOCABULARIES_PATH}...")
        VOCABULARIES_PATH.write_text(format_vocabularies(new), encoding="utf-8")
    else:
        print("No changes.")


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse the command line arguments."""
    parser = argparse.ArgumentParser(
        prog="update_zenodo_vocabularies.py",
        description="Regenerate stepup/reprep/zenodo_vocabularies.yaml from the Zenodo API.",
    )
    parser.add_argument(
        "names",
        nargs="*",
        help="Names of vocabularies to add to the data file, "
        "e.g. licenses. The ones already present are always refreshed.",
    )
    return parser.parse_args(argv)


def download_vocabulary(name: str) -> list[str]:
    """Download all identifiers of one vocabulary from the Zenodo API.

    Parameters
    ----------
    name
        The name of the vocabulary in Zenodo's API, e.g. `licenses`.

    Returns
    -------
    identifiers
        The sorted identifiers of the vocabulary.
    """
    identifiers = set()
    url = f"{API_URL}/{name}?size={PAGE_SIZE}"
    while url is not None:
        res = requests.get(url, timeout=60)
        res.raise_for_status()
        data = res.json()
        identifiers.update(hit["id"] for hit in data["hits"]["hits"])
        url = data.get("links", {}).get("next")
    if len(identifiers) == 0:
        raise ValueError(f"The vocabulary {name} is empty. Is the name correct?")
    return sorted(identifiers)


def format_vocabularies(vocabularies: dict[str, list[str]]) -> str:
    """Format the vocabularies as the contents of the data file."""
    lines = [HEADER.format(date=datetime.date.today().isoformat())]
    for name, identifiers in sorted(vocabularies.items()):
        lines.append(f'"{name}":\n')
        lines.extend(f'  - "{identifier}"\n' for identifier in identifiers)
    return "".join(lines)


def report(old: dict[str, list[str]], new: dict[str, list[str]]) -> bool:
    """Print the added and removed identifiers per vocabulary."""
    changed = False
    for name, identifiers in sorted(new.items()):
        added = sorted(set(identifiers) - set(old.get(name, [])))
        removed = sorted(set(old.get(name, [])) - set(identifiers))
        print(f"{name}: {len(identifiers)} identifiers, +{len(added)} -{len(removed)}")
        for identifier in added:
            print(f"  + {identifier}")
            changed = True
        for identifier in removed:
            print(f"  - {identifier}")
            changed = True

    return changed


if __name__ == "__main__":
    sys.exit(main())
