name: pytest
on:
  push:
    branches:
     - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install development version
        run: |
          pip install -e .[dev]
          pip install git+https://github.com/reproducible-reporting/stepup-core.git@main
      - name: Run pytest
        run: pytest -vv
