name: pytest
on:
  push:
    branches:
     - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install tools
        run: sudo apt-get install -y inkscape mupdf-tools libreoffice
      - name: Install development version
        run: pip install -e .[dev]
      - name: Run pytest
        run: pytest -vv
